import { useCategoryStore } from "../store/categoryStore";

export const useCategories = () => {
  const {
    categories,
    tree,
    catalogCategories,
    selectedCategory,
    isLoading,
    error,
    currentPage,
    itemsPerPage,
    totalItems,
    totalPages,
    filters,
    fetchAll,
    fetchTree,
    fetchCatalogCategories,
    createCategory,
    updateCategory,
    deleteCategory,
    setPage,
    setItemsPerPage,
    clearError,
    setFilters,
    clearFilters,
  } = useCategoryStore();

  return {
    categories,
    tree,
    catalogCategories,
    selectedCategory,
    isLoading,
    error,
    currentPage,
    itemsPerPage,
    totalItems,
    totalPages,
    filters,
    fetchAll,
    fetchTree,
    fetchCatalogCategories,
    createCategory,
    updateCategory,
    deleteCategory,
    setPage,
    setItemsPerPage,
    clearError,
    setFilters,
    clearFilters,
  };
};
